Repository powsybl/powsybl-open-loadflow, pull requests merged in 2022-03, with the labels that each got.

#449 Security analysis new parameters support
  src/main/java/com/powsybl/openloadflow/sa/AbstractSecurityAnalysis.java
  src/main/java/com/powsybl/openloadflow/sa/AcSecurityAnalysis.java
  src/main/java/com/powsybl/openloadflow/sa/DcSecurityAnalysis.java
  src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisTest.java
Labels: PR: next-release

#462 Refactor min impedance detection
  src/main/java/com/powsybl/openloadflow/OpenLoadFlowProvider.java
  src/main/java/com/powsybl/openloadflow/ac/VoltageMagnitudeInitializer.java
  src/main/java/com/powsybl/openloadflow/ac/equations/AcEquationSystem.java
  src/main/java/com/powsybl/openloadflow/dc/equations/DcEquationSystem.java
  src/main/java/com/powsybl/openloadflow/network/LfBranch.java
  src/main/java/com/powsybl/openloadflow/network/LfNetwork.java
  src/main/java/com/powsybl/openloadflow/network/impl/AbstractLfBranch.java
  src/main/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImpl.java
  src/test/java/com/powsybl/openloadflow/network/impl/LfSwitchTest.java
Labels: PR: next-release

#460 Fix KLU issue with regulating phase shifter necessary for connectivity
  src/main/java/com/powsybl/openloadflow/ac/PhaseControlOuterLoop.java
  src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowPhaseShifterTest.java
  src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisTest.java
Labels: bug

#469 Fix parameters loading
  src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java
  src/main/java/com/powsybl/openloadflow/sensi/OpenSensitivityAnalysisProvider.java
Labels: bug

#468 Fix contingency apply for DC sensitivity calculation and reference flows calculation in case of ZERO status
  src/main/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysis.java
  src/test/java/com/powsybl/openloadflow/sensi/dc/DcSensitivityAnalysisContingenciesTest.java
Labels: bug

#487 Fix transformer voltage control with multiple components
  src/main/java/com/powsybl/openloadflow/ac/TransformerVoltageControlOuterLoop.java
  src/main/java/com/powsybl/openloadflow/network/AbstractElement.java
  src/main/java/com/powsybl/openloadflow/network/LfElement.java
  src/main/java/com/powsybl/openloadflow/network/LfNetwork.java
  src/test/java/com/powsybl/openloadflow/network/UserObjectTest.java
Labels: bug, PR: next-release
