Repository powsybl/powsybl-open-loadflow, pull requests merged in 2023-11, with the labels that each got.

#892 Fix missing voltage limit violations
  src/main/java/com/powsybl/openloadflow/sa/LimitViolationManager.java
  src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisTest.java
Labels: PR: next-release

#879 Fix incremental outer loops
  src/main/java/com/powsybl/openloadflow/ac/outerloop/IncrementalShuntVoltageControlOuterLoop.java
  src/main/java/com/powsybl/openloadflow/ac/outerloop/IncrementalTransformerVoltageControlOuterLoop.java
  src/main/java/com/powsybl/openloadflow/lf/outerloop/IncrementalContextData.java
  src/main/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImpl.java
  src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowShuntTest.java
  src/test/java/com/powsybl/openloadflow/network/ShuntNetworkFactory.java
  src/test/java/com/powsybl/openloadflow/network/VoltageControlNetworkFactory.java
  src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisTest.java
Labels: PR: next-release, ready-for-review

#625 Fix not same variable and equation issue
  src/main/java/com/powsybl/openloadflow/network/LfBus.java
  src/main/java/com/powsybl/openloadflow/network/LfZeroImpedanceNetwork.java
  src/main/java/com/powsybl/openloadflow/network/VoltageControl.java
  src/main/java/com/powsybl/openloadflow/network/impl/AbstractLfBus.java
  src/test/java/com/powsybl/openloadflow/ac/NotSameNumberVariableEquationIssueTest.java
Labels: bug, PR: next-release

#890 Slack Distribution Failure behavior
  src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java
  src/main/java/com/powsybl/openloadflow/ac/AcLoadFlowParameters.java
  src/main/java/com/powsybl/openloadflow/ac/AcLoadFlowResult.java
  src/main/java/com/powsybl/openloadflow/ac/AcloadFlowEngine.java
  src/main/java/com/powsybl/openloadflow/ac/outerloop/DistributedSlackOuterLoop.java
  src/main/java/com/powsybl/openloadflow/lf/outerloop/OuterLoopStatus.java
  src/main/java/com/powsybl/openloadflow/sa/AbstractSecurityAnalysis.java
  src/main/java/com/powsybl/openloadflow/sa/AcSecurityAnalysis.java
  src/test/java/com/powsybl/openloadflow/OpenLoadFlowParametersTest.java
  src/test/java/com/powsybl/openloadflow/OpenLoadFlowProviderTest.java
  src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowPhaseShifterTest.java
  src/test/java/com/powsybl/openloadflow/ac/DistributedSlackOnGenerationTest.java
  src/test/java/com/powsybl/openloadflow/ac/DistributedSlackOnLoadTest.java
  src/test/java/com/powsybl/openloadflow/ac/NonImpedantBranchWithBreakerIssueTest.java
  src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisTest.java
  src/test/resources/debug-parameters.json
Labels: PR: next-release, ready-for-review

#811 Substation automation system
  src/main/java/com/powsybl/openloadflow/AbstractAcOuterLoopConfig.java
  src/main/java/com/powsybl/openloadflow/DefaultAcOuterLoopConfig.java
  src/main/java/com/powsybl/openloadflow/ExplicitAcOuterLoopConfig.java
  src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java
  src/main/java/com/powsybl/openloadflow/OpenLoadFlowProvider.java
  src/main/java/com/powsybl/openloadflow/ac/AcloadFlowEngine.java
  src/main/java/com/powsybl/openloadflow/ac/outerloop/AutomationSystemOuterLoop.java
  src/main/java/com/powsybl/openloadflow/graph/EvenShiloachGraphDecrementalConnectivity.java
  src/main/java/com/powsybl/openloadflow/graph/GraphConnectivity.java
  src/main/java/com/powsybl/openloadflow/graph/MinimumSpanningTreeGraphConnectivity.java
  src/main/java/com/powsybl/openloadflow/graph/NaiveGraphConnectivity.java
  src/main/java/com/powsybl/openloadflow/network/LfNetwork.java
  src/main/java/com/powsybl/openloadflow/network/LfNetworkParameters.java
  src/main/java/com/powsybl/openloadflow/network/LfOverloadManagementSystem.java
  src/main/java/com/powsybl/openloadflow/network/LfTopoConfig.java
  src/main/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImpl.java
  src/main/java/com/powsybl/openloadflow/network/impl/Networks.java
  src/main/java/com/powsybl/openloadflow/network/impl/extensions/OverloadManagementSystem.java
  src/main/java/com/powsybl/openloadflow/network/impl/extensions/OverloadManagementSystemAdder.java
  src/main/java/com/powsybl/openloadflow/network/impl/extensions/OverloadManagementSystemAdderImpl.java
  src/main/java/com/powsybl/openloadflow/network/impl/extensions/OverloadManagementSystemImpl.java
  src/main/java/com/powsybl/openloadflow/network/impl/extensions/SubstationAutomationSystems.java
  src/main/java/com/powsybl/openloadflow/network/impl/extensions/SubstationAutomationSystemsAdder.java
  src/main/java/com/powsybl/openloadflow/network/impl/extensions/SubstationAutomationSystemsAdderImpl.java
  src/main/java/com/powsybl/openloadflow/network/impl/extensions/SubstationAutomationSystemsAdderImplProvider.java
  src/main/java/com/powsybl/openloadflow/network/impl/extensions/SubstationAutomationSystemsImpl.java
  src/main/java/com/powsybl/openloadflow/network/impl/extensions/SubstationAutomationSystemsXmlSerializer.java
  src/main/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisProvider.java
  src/main/java/com/powsybl/openloadflow/sensi/AcSensitivityAnalysis.java
  src/test/java/com/powsybl/openloadflow/OpenLoadFlowParametersTest.java
  src/test/java/com/powsybl/openloadflow/OpenLoadFlowProviderTest.java
  src/test/java/com/powsybl/openloadflow/ac/AutomationSystemTest.java
  src/test/java/com/powsybl/openloadflow/network/AbstractLoadFlowNetworkFactory.java
  src/test/java/com/powsybl/openloadflow/network/AutomationSystemNetworkFactory.java
  src/test/java/com/powsybl/openloadflow/network/impl/extensions/SubstationAutomationSystemsTest.java
  src/test/resources/debug-parameters.json
  src/test/resources/substationAutomationSystemsRef.xml
  src/test/resources/xsd/substationAutomationSystems.xsd
Labels: ready-for-review

#904 Fix update reactive keys for voltage control
  src/main/java/com/powsybl/openloadflow/network/LfContingency.java
  src/test/java/com/powsybl/openloadflow/network/FourBusNetworkFactory.java
  src/test/java/com/powsybl/openloadflow/network/VoltageControlNetworkFactory.java
  src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisTest.java
Labels: bug

#895 Improve performance of incremental outer loops
  src/main/java/com/powsybl/openloadflow/ac/outerloop/IncrementalShuntVoltageControlOuterLoop.java
  src/main/java/com/powsybl/openloadflow/ac/outerloop/IncrementalTransformerVoltageControlOuterLoop.java
  src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowTransformerControlTest.java
Labels: enhancement

#914 Refactor reactive power control
  src/main/java/com/powsybl/openloadflow/ac/AcTargetVector.java
  src/main/java/com/powsybl/openloadflow/ac/equations/AcEquationSystemCreator.java
  src/main/java/com/powsybl/openloadflow/ac/equations/AcEquationSystemUpdater.java
  src/main/java/com/powsybl/openloadflow/ac/equations/asym/AsymmetricalAcEquationSystemCreator.java
  src/main/java/com/powsybl/openloadflow/ac/outerloop/ReactiveLimitsOuterLoop.java
  src/main/java/com/powsybl/openloadflow/network/AbstractLfNetworkListener.java
  src/main/java/com/powsybl/openloadflow/network/BusState.java
  src/main/java/com/powsybl/openloadflow/network/GeneratorReactivePowerControl.java
  src/main/java/com/powsybl/openloadflow/network/LfBranch.java
  src/main/java/com/powsybl/openloadflow/network/LfBus.java
  src/main/java/com/powsybl/openloadflow/network/LfContingency.java
  src/main/java/com/powsybl/openloadflow/network/LfNetworkListener.java
  src/main/java/com/powsybl/openloadflow/network/LfNetworkListenerTracer.java
  src/main/java/com/powsybl/openloadflow/network/impl/AbstractLfBranch.java
  src/main/java/com/powsybl/openloadflow/network/impl/AbstractLfBus.java
  src/main/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImpl.java
  src/test/java/com/powsybl/openloadflow/ac/GeneratorRemoteControlTest.java
Labels: refactoring
