Repository powsybl/powsybl-open-loadflow, pull requests merged in 2023-04, with the labels that each got.

#740 Add Newton Raphson report
  src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java
  src/main/java/com/powsybl/openloadflow/OpenLoadFlowProvider.java
  src/main/java/com/powsybl/openloadflow/ac/AcloadFlowEngine.java
  src/main/java/com/powsybl/openloadflow/ac/nr/NewtonRaphson.java
  src/main/java/com/powsybl/openloadflow/ac/nr/NewtonRaphsonParameters.java
  src/main/java/com/powsybl/openloadflow/sa/AcSecurityAnalysis.java
  src/main/java/com/powsybl/openloadflow/sensi/AcSensitivityAnalysis.java
  src/main/java/com/powsybl/openloadflow/util/Reports.java
  src/test/java/com/powsybl/openloadflow/OpenLoadFlowParametersTest.java
  src/test/java/com/powsybl/openloadflow/OpenLoadFlowProviderTest.java
  src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowReportTest.java
  src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisTest.java
  src/test/java/com/powsybl/openloadflow/sensi/ac/AcSensitivityAnalysisReportTest.java
  src/test/java/com/powsybl/openloadflow/util/LoadFlowAssert.java
  src/test/resources/debug-parameters.json
  src/test/resources/detailedNrReportSecurityAnalysis.txt
  src/test/resources/esgTutoReportDetailedNrReportLf.txt
  src/test/resources/esgTutoReportDetailedNrReportSensi.txt
Labels: enhancement, PR: next-release

#650 Test Metrix for violations in Current, Voltage, Active and Apparent Power
  src/test/java/com/powsybl/openloadflow/network/MetrixTutorialSixBusesSecurityAnalysisFactory.java
  src/test/java/com/powsybl/openloadflow/sa/AbstractOpenSecurityAnalysisTest.java
  src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisTest.java
  src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisWithActionsTest.java
Labels: ready-for-review

#768 Fix no impact load contingency when simulated with a switch contingency
  src/main/java/com/powsybl/openloadflow/network/PowerShift.java
  src/main/java/com/powsybl/openloadflow/network/impl/PropagatedContingency.java
  src/main/java/com/powsybl/openloadflow/sa/AcSecurityAnalysis.java
  src/main/java/com/powsybl/openloadflow/sa/DcSecurityAnalysis.java
  src/main/java/com/powsybl/openloadflow/sensi/AcSensitivityAnalysis.java
  src/main/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysis.java
  src/main/java/com/powsybl/openloadflow/sensi/OpenSensitivityAnalysisProvider.java
  src/test/java/com/powsybl/openloadflow/sa/LfActionTest.java
  src/test/java/com/powsybl/openloadflow/sa/LfContingencyTest.java
  src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisGraphTest.java
  src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisTest.java
  src/test/java/com/powsybl/openloadflow/sensi/dc/DcSensitivityAnalysisTest.java
Labels: bug
