Repository powsybl/powsybl-open-loadflow, pull requests merged in 2023-08, with the labels that each got.

#770 DC PST active power control
  src/main/java/com/powsybl/openloadflow/DefaultAcOuterLoopConfig.java
  src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java
  src/main/java/com/powsybl/openloadflow/ac/AcLoadFlowResult.java
  src/main/java/com/powsybl/openloadflow/ac/AcloadFlowEngine.java
  src/main/java/com/powsybl/openloadflow/ac/outerloop/AcIncrementalPhaseControlOuterLoop.java
  src/main/java/com/powsybl/openloadflow/ac/outerloop/IncrementalShuntVoltageControlOuterLoop.java
  src/main/java/com/powsybl/openloadflow/ac/outerloop/IncrementalTransformerVoltageControlOuterLoop.java
  src/main/java/com/powsybl/openloadflow/ac/outerloop/PhaseControlOuterLoop.java
  src/main/java/com/powsybl/openloadflow/dc/DcIncrementalPhaseControlOuterLoop.java
  src/main/java/com/powsybl/openloadflow/dc/DcLoadFlowEngine.java
  src/main/java/com/powsybl/openloadflow/dc/DcLoadFlowParameters.java
  src/main/java/com/powsybl/openloadflow/dc/DcOuterLoopContext.java
  src/main/java/com/powsybl/openloadflow/dc/DcValueVoltageInitializer.java
  src/main/java/com/powsybl/openloadflow/dc/equations/DcEquationSystemCreationParameters.java
  src/main/java/com/powsybl/openloadflow/dc/equations/DcEquationSystemCreator.java
  src/main/java/com/powsybl/openloadflow/lf/outerloop/AbstractIncrementalPhaseControlOuterLoop.java
  src/main/java/com/powsybl/openloadflow/lf/outerloop/AbstractPhaseControlOuterLoop.java
  src/main/java/com/powsybl/openloadflow/lf/outerloop/IncrementalContextData.java
  src/main/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysis.java
  src/test/java/com/powsybl/openloadflow/FullVoltageInitializerTest.java
  src/test/java/com/powsybl/openloadflow/OpenLoadFlowProviderTest.java
  src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowPhaseShifterTest.java
  src/test/java/com/powsybl/openloadflow/ac/DcValueVoltageInitializerTest.java
  src/test/java/com/powsybl/openloadflow/dc/DcLoadFlowMatrixTest.java
  src/test/java/com/powsybl/openloadflow/dc/DcLoadFlowTest.java
  src/test/java/com/powsybl/openloadflow/equations/EquationSystemTest.java
Labels: PR: next-release

#824 Fix dcUseTransformerRatio not taken into account in DC sensi
  src/main/java/com/powsybl/openloadflow/dc/equations/AbstractClosedBranchDcFlowEquationTerm.java
  src/main/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysis.java
  src/test/java/com/powsybl/openloadflow/sensi/AbstractSensitivityAnalysisTest.java
  src/test/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysisContingenciesTest.java
Labels: bug

#822 Fix too large dense matrix allocation issue
  src/main/java/com/powsybl/openloadflow/sensi/AbstractSensitivityAnalysis.java
  src/main/java/com/powsybl/openloadflow/sensi/AcSensitivityAnalysis.java
  src/main/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysis.java
  src/test/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysisTest.java
Labels: bug

#825 Get slack from network in sensi analysis
  src/main/java/com/powsybl/openloadflow/sensi/AcSensitivityAnalysis.java
  src/main/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysis.java
Labels: bug, PR: next-release

#829 Improve performance of reference flow calculation in a DC sensi analysis
  src/main/java/com/powsybl/openloadflow/dc/DcLoadFlowEngine.java
  src/main/java/com/powsybl/openloadflow/dc/equations/AbstractClosedBranchDcFlowEquationTerm.java
  src/main/java/com/powsybl/openloadflow/dc/equations/ClosedBranchSide1DcFlowEquationTerm.java
  src/main/java/com/powsybl/openloadflow/dc/equations/ClosedBranchSide2DcFlowEquationTerm.java
  src/main/java/com/powsybl/openloadflow/equations/EquationTerm.java
  src/main/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysis.java
Labels: PR: next-release, performance

#835 Fix NPE in remote reactive power control
  src/main/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImpl.java
  src/test/java/com/powsybl/openloadflow/ac/GeneratorRemoteControlTest.java
Labels: bug, PR: next-release, PR: waiting-for-review

#828 Fix small reference flow values instead of strict zero
  src/main/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysis.java
  src/test/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysisContingenciesTest.java
Labels: bug, PR: next-release
