Repository powsybl/powsybl-open-loadflow, pull requests merged in 2023-06, with the labels that each got.

#799 Exception: No more <elementType> participating to slack distribution
  src/main/java/com/powsybl/openloadflow/network/util/ActivePowerDistribution.java
  src/main/java/com/powsybl/openloadflow/network/util/GenerationActivePowerDistributionStep.java
  src/main/java/com/powsybl/openloadflow/network/util/LoadActivePowerDistributionStep.java
  src/main/java/com/powsybl/openloadflow/network/util/ParticipatingElement.java
  src/main/java/com/powsybl/openloadflow/sensi/AbstractSensitivityAnalysis.java
  src/main/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysis.java
  src/test/java/com/powsybl/openloadflow/ac/DistributedSlackOnLoadTest.java
Labels: PR: next-release

#800 Fix power factor constant with conform loads
  src/main/java/com/powsybl/openloadflow/network/impl/AbstractLfBus.java
  src/test/java/com/powsybl/openloadflow/ac/DistributedSlackOnLoadTest.java
  src/test/java/com/powsybl/openloadflow/network/DistributedSlackNetworkFactory.java
Labels: bug, PR: next-release

#796 Add secondary voltage control, voltage sensi epsilon parameter
  src/main/java/com/powsybl/openloadflow/DefaultAcOuterLoopConfig.java
  src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java
  src/main/java/com/powsybl/openloadflow/ac/outerloop/SecondaryVoltageControlOuterLoop.java
  src/main/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImpl.java
  src/test/java/com/powsybl/openloadflow/OpenLoadFlowParametersTest.java
  src/test/java/com/powsybl/openloadflow/OpenLoadFlowProviderTest.java
  src/test/java/com/powsybl/openloadflow/ac/SecondaryVoltageControlTest.java
  src/test/resources/debug-parameters.json
Labels: PR: next-release

#808 Clean indexed terms when removing an equation
  src/main/java/com/powsybl/openloadflow/equations/EquationSystem.java
  src/test/java/com/powsybl/openloadflow/equations/EquationSystemTest.java
Labels: bug
