Repository powsybl/powsybl-open-loadflow, pull requests merged in 2024-01, with the labels that each got.

#941 Fix sharing of reactive power with for multiple generators with ReactivePowerControl
  src/main/java/com/powsybl/openloadflow/network/impl/AbstractLfBus.java
  src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowEurostagTutorialExample1Test.java
  src/test/java/com/powsybl/openloadflow/ac/GeneratorRemoteControlTest.java
  src/test/java/com/powsybl/openloadflow/network/impl/LfBusImplTest.java
Labels: bug

#907 Transformer RatioTapChanger reactive power control
  src/main/java/com/powsybl/openloadflow/AbstractAcOuterLoopConfig.java
  src/main/java/com/powsybl/openloadflow/DefaultAcOuterLoopConfig.java
  src/main/java/com/powsybl/openloadflow/ExplicitAcOuterLoopConfig.java
  src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java
  src/main/java/com/powsybl/openloadflow/OpenLoadFlowProvider.java
  src/main/java/com/powsybl/openloadflow/ac/equations/AcEquationSystemCreator.java
  src/main/java/com/powsybl/openloadflow/ac/equations/asym/AsymmetricalAcEquationSystemCreator.java
  src/main/java/com/powsybl/openloadflow/ac/outerloop/AbstractTransformerReactivePowerControlOuterLoop.java
  src/main/java/com/powsybl/openloadflow/ac/outerloop/IncrementalTransformerReactivePowerControlOuterLoop.java
  src/main/java/com/powsybl/openloadflow/ac/outerloop/IncrementalTransformerVoltageControlOuterLoop.java
  src/main/java/com/powsybl/openloadflow/lf/outerloop/IncrementalContextData.java
  src/main/java/com/powsybl/openloadflow/network/GeneratorReactivePowerControl.java
  src/main/java/com/powsybl/openloadflow/network/LfBranch.java
  src/main/java/com/powsybl/openloadflow/network/LfNetwork.java
  src/main/java/com/powsybl/openloadflow/network/LfNetworkParameters.java
  src/main/java/com/powsybl/openloadflow/network/LfNetworkStateUpdateParameters.java
  src/main/java/com/powsybl/openloadflow/network/ReactivePowerControl.java
  src/main/java/com/powsybl/openloadflow/network/TransformerReactivePowerControl.java
  src/main/java/com/powsybl/openloadflow/network/impl/AbstractLfBranch.java
  src/main/java/com/powsybl/openloadflow/network/impl/LfBranchImpl.java
  src/main/java/com/powsybl/openloadflow/network/impl/LfGeneratorImpl.java
  src/main/java/com/powsybl/openloadflow/network/impl/LfLegBranch.java
  src/main/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImpl.java
  src/main/java/com/powsybl/openloadflow/network/impl/LfNetworkLoadingReport.java
  src/main/java/com/powsybl/openloadflow/sensi/AcSensitivityAnalysis.java
  src/main/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysis.java
  src/test/java/com/powsybl/openloadflow/OpenLoadFlowParametersTest.java
  src/test/java/com/powsybl/openloadflow/OpenLoadFlowProviderTest.java
  src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowTransformerReactivePowerControlTest.java
  src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowTransformerVoltageControlTest.java
  src/test/java/com/powsybl/openloadflow/ac/GeneratorRemoteControlTest.java
  src/test/java/com/powsybl/openloadflow/ac/NonImpedantBranchWithBreakerIssueTest.java
  src/test/java/com/powsybl/openloadflow/network/ReactivePowerControlNetworkFactory.java
  src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisTest.java
  src/test/resources/debug-parameters.json
Labels: PR: next-release

#922 Update README
  README.md
Labels: PR: next-release

#899 Generator reference priorities
  src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java
  src/main/java/com/powsybl/openloadflow/OpenLoadFlowProvider.java
  src/main/java/com/powsybl/openloadflow/network/LfGenerator.java
  src/main/java/com/powsybl/openloadflow/network/LfNetwork.java
  src/main/java/com/powsybl/openloadflow/network/LfNetworkParameters.java
  src/main/java/com/powsybl/openloadflow/network/LfNetworkStateUpdateParameters.java
  src/main/java/com/powsybl/openloadflow/network/LfReferencePriorityInjection.java
  src/main/java/com/powsybl/openloadflow/network/ReferenceBusFirstSlackSelector.java
  src/main/java/com/powsybl/openloadflow/network/ReferenceBusGeneratorPrioritySelector.java
  src/main/java/com/powsybl/openloadflow/network/ReferenceBusSelectionMode.java
  src/main/java/com/powsybl/openloadflow/network/ReferenceBusSelector.java
  src/main/java/com/powsybl/openloadflow/network/SelectedGeneratorReferenceBus.java
  src/main/java/com/powsybl/openloadflow/network/SelectedReferenceBus.java
  src/main/java/com/powsybl/openloadflow/network/impl/AbstractLfGenerator.java
  src/main/java/com/powsybl/openloadflow/network/impl/LfBatteryImpl.java
  src/main/java/com/powsybl/openloadflow/network/impl/LfDanglingLineGenerator.java
  src/main/java/com/powsybl/openloadflow/network/impl/LfGeneratorImpl.java
  src/main/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImpl.java
  src/main/java/com/powsybl/openloadflow/network/impl/LfStaticVarCompensatorImpl.java
  src/main/java/com/powsybl/openloadflow/network/impl/LfVscConverterStationImpl.java
  src/main/java/com/powsybl/openloadflow/sa/AcSecurityAnalysis.java
  src/main/java/com/powsybl/openloadflow/sa/DcSecurityAnalysis.java
  src/main/java/com/powsybl/openloadflow/sensi/AcSensitivityAnalysis.java
  src/main/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysis.java
  src/test/java/com/powsybl/openloadflow/OpenLoadFlowParametersTest.java
  src/test/java/com/powsybl/openloadflow/OpenLoadFlowProviderTest.java
  src/test/java/com/powsybl/openloadflow/ac/NonImpedantBranchWithBreakerIssueTest.java
  src/test/java/com/powsybl/openloadflow/ac/ReferenceBusPrioritiesTest.java
  src/test/java/com/powsybl/openloadflow/network/impl/LfBusImplTest.java
  src/test/resources/debug-parameters.json
Labels: PR: next-release

#963 Bug fix in AC emulation: consider P0 to define controller
  src/main/java/com/powsybl/openloadflow/ac/equations/HvdcAcEmulationSide1ActiveFlowEquationTerm.java
  src/main/java/com/powsybl/openloadflow/ac/equations/HvdcAcEmulationSide2ActiveFlowEquationTerm.java
  src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowVscTest.java
  src/test/java/com/powsybl/openloadflow/network/HvdcNetworkFactory.java
Labels: bug, PR: next-release

#961 Loss of a VSC converter station after contingency
  src/main/java/com/powsybl/openloadflow/ac/equations/AcEquationSystemCreator.java
  src/main/java/com/powsybl/openloadflow/network/HvdcState.java
  src/main/java/com/powsybl/openloadflow/network/LfAction.java
  src/main/java/com/powsybl/openloadflow/network/LfBus.java
  src/main/java/com/powsybl/openloadflow/network/LfContingency.java
  src/main/java/com/powsybl/openloadflow/network/LfHvdc.java
  src/main/java/com/powsybl/openloadflow/network/impl/AbstractLfBus.java
  src/main/java/com/powsybl/openloadflow/network/impl/LfHvdcImpl.java
  src/main/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImpl.java
  src/main/java/com/powsybl/openloadflow/network/impl/LfVscConverterStationImpl.java
  src/main/java/com/powsybl/openloadflow/network/impl/PropagatedContingency.java
  src/main/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysis.java
  src/test/java/com/powsybl/openloadflow/network/HvdcNetworkFactory.java
  src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisTest.java
  src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisWithActionsTest.java
  src/test/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysisContingenciesTest.java
Labels: PR: next-release

#959 New SlackDistributionFailureBehavior DISTRIBUTE_ON_REFERENCE_GENERATOR
  src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java
  src/main/java/com/powsybl/openloadflow/ac/outerloop/DistributedSlackOuterLoop.java
  src/test/java/com/powsybl/openloadflow/ac/DistributedSlackOnGenerationTest.java
Labels: PR: next-release

#964 Optionally disable voltage regulation of generators with targetP outside Pmin/Pmax
  src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java
  src/main/java/com/powsybl/openloadflow/network/LfNetworkParameters.java
  src/main/java/com/powsybl/openloadflow/network/impl/AbstractLfGenerator.java
  src/main/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImpl.java
  src/main/java/com/powsybl/openloadflow/network/impl/LfNetworkLoadingReport.java
  src/main/java/com/powsybl/openloadflow/util/Reports.java
  src/test/java/com/powsybl/openloadflow/OpenLoadFlowParametersTest.java
  src/test/java/com/powsybl/openloadflow/OpenLoadFlowProviderTest.java
  src/test/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImplTest.java
  src/test/resources/debug-parameters.json
Labels: enhancement

#966 Fast restart for secondary voltage control
  src/main/java/com/powsybl/openloadflow/NetworkCache.java
  src/main/java/com/powsybl/openloadflow/network/LfNetwork.java
  src/main/java/com/powsybl/openloadflow/network/LfSecondaryVoltageControl.java
  src/main/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImpl.java
  src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowWithCachingTest.java
Labels: PR: next-release

#967 Fast restart for transformer target voltage change
  src/main/java/com/powsybl/openloadflow/NetworkCache.java
  src/main/java/com/powsybl/openloadflow/equations/TargetVector.java
  src/main/java/com/powsybl/openloadflow/network/AbstractLfNetworkListener.java
  src/main/java/com/powsybl/openloadflow/network/LfNetworkListener.java
  src/main/java/com/powsybl/openloadflow/network/LfNetworkListenerTracer.java
  src/main/java/com/powsybl/openloadflow/network/TransformerVoltageControl.java
  src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowWithCachingTest.java
Labels: PR: next-release

#968 Fix OpenLoadFlowParameters equals and clone
  src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java
  src/test/java/com/powsybl/openloadflow/OpenLoadFlowParametersTest.java
Labels: PR: next-release

#943 Added support of action to reconnect branch at both side action
  src/main/java/com/powsybl/openloadflow/network/LfAction.java
  src/main/java/com/powsybl/openloadflow/network/LfTopoConfig.java
  src/main/java/com/powsybl/openloadflow/network/impl/Networks.java
  src/main/java/com/powsybl/openloadflow/sa/AbstractSecurityAnalysis.java
  src/test/java/com/powsybl/openloadflow/sa/LfActionTest.java
  src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisWithActionsTest.java
Labels: PR: next-release

#965 Fix flow computation of HVDC connected at only one side
  src/main/java/com/powsybl/openloadflow/network/impl/AbstractLfBus.java
  src/main/java/com/powsybl/openloadflow/network/impl/HvdcConverterStations.java
  src/main/java/com/powsybl/openloadflow/network/impl/LfVscConverterStationImpl.java
  src/main/java/com/powsybl/openloadflow/network/impl/Networks.java
  src/main/java/com/powsybl/openloadflow/network/impl/PropagatedContingency.java
  src/main/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysis.java
  src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowVscTest.java
  src/test/java/com/powsybl/openloadflow/network/HvdcNetworkFactory.java
  src/test/java/com/powsybl/openloadflow/network/LfNetworkTest.java
  src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisWithActionsTest.java
Labels: PR: next-release
