Repository powsybl/powsybl-open-loadflow, pull requests merged in 2024-03, with the labels that each got.

#955 Configuration of voltage target priority
  src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java
  src/main/java/com/powsybl/openloadflow/ac/AcTargetVector.java
  src/main/java/com/powsybl/openloadflow/ac/outerloop/IncrementalShuntVoltageControlOuterLoop.java
  src/main/java/com/powsybl/openloadflow/ac/outerloop/IncrementalTransformerVoltageControlOuterLoop.java
  src/main/java/com/powsybl/openloadflow/network/DiscreteVoltageControl.java
  src/main/java/com/powsybl/openloadflow/network/GeneratorVoltageControl.java
  src/main/java/com/powsybl/openloadflow/network/LfBus.java
  src/main/java/com/powsybl/openloadflow/network/LfNetworkParameters.java
  src/main/java/com/powsybl/openloadflow/network/ShuntVoltageControl.java
  src/main/java/com/powsybl/openloadflow/network/TransformerVoltageControl.java
  src/main/java/com/powsybl/openloadflow/network/VoltageControl.java
  src/main/java/com/powsybl/openloadflow/network/impl/AbstractLfBus.java
  src/main/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImpl.java
  src/test/java/com/powsybl/openloadflow/OpenLoadFlowParametersTest.java
  src/test/java/com/powsybl/openloadflow/OpenLoadFlowProviderTest.java
  src/test/java/com/powsybl/openloadflow/ac/VoltageTargetPrioritiesTest.java
  src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisTest.java
  src/test/resources/debug-parameters.json
Labels: PR: next-release

#977 Improve AC Load Flow reports
  src/main/java/com/powsybl/openloadflow/ac/AcOuterLoopContext.java
  src/main/java/com/powsybl/openloadflow/ac/AcloadFlowEngine.java
  src/main/java/com/powsybl/openloadflow/ac/outerloop/AcIncrementalPhaseControlOuterLoop.java
  src/main/java/com/powsybl/openloadflow/ac/outerloop/DistributedSlackOuterLoop.java
  src/main/java/com/powsybl/openloadflow/ac/outerloop/IncrementalShuntVoltageControlOuterLoop.java
  src/main/java/com/powsybl/openloadflow/ac/outerloop/IncrementalTransformerReactivePowerControlOuterLoop.java
  src/main/java/com/powsybl/openloadflow/ac/outerloop/IncrementalTransformerVoltageControlOuterLoop.java
  src/main/java/com/powsybl/openloadflow/ac/outerloop/ReactiveLimitsOuterLoop.java
  src/main/java/com/powsybl/openloadflow/ac/solver/LineSearchStateVectorScaling.java
  src/main/java/com/powsybl/openloadflow/ac/solver/MaxVoltageChangeStateVectorScaling.java
  src/main/java/com/powsybl/openloadflow/ac/solver/NewtonRaphson.java
  src/main/java/com/powsybl/openloadflow/ac/solver/NoneStateVectorScaling.java
  src/main/java/com/powsybl/openloadflow/ac/solver/StateVectorScaling.java
  src/main/java/com/powsybl/openloadflow/dc/DcIncrementalPhaseControlOuterLoop.java
  src/main/java/com/powsybl/openloadflow/lf/outerloop/AbstractIncrementalPhaseControlOuterLoop.java
  src/main/java/com/powsybl/openloadflow/network/LfNetwork.java
  src/main/java/com/powsybl/openloadflow/util/Reports.java
  src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowEurostagTutorialExample1Test.java
  src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowReportTest.java
  src/test/resources/detailedNrReportSecurityAnalysis.txt
  src/test/resources/esgTutoReport.txt
  src/test/resources/esgTutoReportDetailedNrReportLf.txt
  src/test/resources/esgTutoReportDetailedNrReportSensi.txt
  src/test/resources/logback-test.xml
  src/test/resources/saReport.txt
  src/test/resources/shuntVoltageControlOuterLoopReport.txt
  src/test/resources/transformerReactivePowerControlOuterLoopReport.txt
Labels: enhancement, PR: next-release

#994 Network slack bus selector multi-variant support/bug
  src/main/java/com/powsybl/openloadflow/network/NetworkSlackBusSelector.java
  src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowEurostagTutorialExample1Test.java
Labels: bug

#1002 Add unit test with VSC voltage control and targetP = 0
  src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowVscTest.java
Labels: PR: next-release

#999 NR mismatch reporter: add unit in mismatches
  src/main/java/com/powsybl/openloadflow/util/Reports.java
  src/test/resources/detailedNrReportSecurityAnalysis.txt
  src/test/resources/esgTutoReportDetailedNrReportLf.txt
  src/test/resources/esgTutoReportDetailedNrReportSensi.txt
  src/test/resources/shuntVoltageControlOuterLoopReport.txt
  src/test/resources/transformerReactivePowerControlOuterLoopReport.txt
Labels: PR: next-release

#1004 Support of VoltageRegulation extension for Battery
  src/main/java/com/powsybl/openloadflow/network/impl/LfBatteryImpl.java
  src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowBatteryTest.java
Labels: PR: next-release

#992 Sensistivity analysis: support sensitivity of reactive injection to a voltage setpoint
  src/main/java/com/powsybl/openloadflow/equations/EquationTerm.java
  src/main/java/com/powsybl/openloadflow/equations/InjectionDerivable.java
  src/main/java/com/powsybl/openloadflow/sensi/AbstractSensitivityAnalysis.java
  src/main/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysis.java
  src/main/java/com/powsybl/openloadflow/util/Derivable.java
  src/test/java/com/powsybl/openloadflow/equations/DerivableTest.java
  src/test/java/com/powsybl/openloadflow/sensi/AbstractSensitivityAnalysisTest.java
  src/test/java/com/powsybl/openloadflow/sensi/AcSensitivityAnalysisTest.java
Labels: PR: next-release

#1003 Fix restoreInitialTopology in SA with multiple SCs
  src/main/java/com/powsybl/openloadflow/network/impl/Networks.java
  src/test/java/com/powsybl/openloadflow/network/FourBusNetworkFactory.java
  src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisWithActionsTest.java
Labels: bug, PR: next-release

#1005 Honnor HVDCOperatorActivePowerRange as well as Pmax of hvdcLine in AC emulation
  src/main/java/com/powsybl/openloadflow/ac/equations/AbstractHvdcAcEmulationFlowEquationTerm.java
  src/main/java/com/powsybl/openloadflow/ac/equations/HvdcAcEmulationSide1ActiveFlowEquationTerm.java
  src/main/java/com/powsybl/openloadflow/ac/equations/HvdcAcEmulationSide2ActiveFlowEquationTerm.java
  src/main/java/com/powsybl/openloadflow/network/LfHvdc.java
  src/main/java/com/powsybl/openloadflow/network/impl/LfHvdcImpl.java
  src/main/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImpl.java
  src/test/java/com/powsybl/openloadflow/EquationsTest.java
  src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowVscTest.java
Labels: PR: next-release
