Repository powsybl/powsybl-open-loadflow, pull requests merged in 2024-12, with the labels that each got.

#1134 add ViolationLocation to LimitViolationManager
  src/main/java/com/powsybl/openloadflow/network/LfBus.java
  src/main/java/com/powsybl/openloadflow/network/impl/AbstractLfBus.java
  src/main/java/com/powsybl/openloadflow/network/impl/LfBusImpl.java
  src/main/java/com/powsybl/openloadflow/network/impl/LfDanglingLineBus.java
  src/main/java/com/powsybl/openloadflow/network/impl/LfStarBus.java
  src/main/java/com/powsybl/openloadflow/sa/LimitViolationManager.java
  src/test/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImplTest.java
  src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisTest.java
Labels: December 2024 release

#1120 fictive load on isolated bus keeps hvdc isolated
  src/main/java/com/powsybl/openloadflow/network/LfBus.java
  src/main/java/com/powsybl/openloadflow/network/LfLoad.java
  src/main/java/com/powsybl/openloadflow/network/impl/AbstractLfBus.java
  src/main/java/com/powsybl/openloadflow/network/impl/HvdcConverterStations.java
  src/main/java/com/powsybl/openloadflow/network/impl/LfLoadImpl.java
  src/main/java/com/powsybl/openloadflow/network/impl/LfVscConverterStationImpl.java
  src/main/java/com/powsybl/openloadflow/network/impl/Networks.java
  src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowVscTest.java
  src/test/java/com/powsybl/openloadflow/network/HvdcNetworkFactory.java
  src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisWithActionsTest.java
  src/test/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysisContingenciesTest.java
Labels: ready-for-review, December 2024 release

#1129 Fix secondary synchronous components in main CC not computed in SA
  src/main/java/com/powsybl/openloadflow/sa/AbstractSecurityAnalysis.java
  src/test/java/com/powsybl/openloadflow/network/ConnectedComponentNetworkFactory.java
  src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisTest.java
Labels: bug, December 2024 release

#1107 Refactor to allow external AC solvers
  pom.xml
  src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java
  src/main/java/com/powsybl/openloadflow/ac/AcLoadFlowParameters.java
  src/main/java/com/powsybl/openloadflow/ac/AcloadFlowEngine.java
  src/main/java/com/powsybl/openloadflow/ac/solver/AcSolverFactory.java
  src/main/java/com/powsybl/openloadflow/ac/solver/AcSolverParameters.java
  src/main/java/com/powsybl/openloadflow/ac/solver/NewtonKrylovFactory.java
  src/main/java/com/powsybl/openloadflow/ac/solver/NewtonKrylovParameters.java
  src/main/java/com/powsybl/openloadflow/ac/solver/NewtonRaphsonFactory.java
  src/main/java/com/powsybl/openloadflow/ac/solver/NewtonRaphsonParameters.java
  src/main/java/com/powsybl/openloadflow/equations/EquationTerm.java
  src/test/java/com/powsybl/openloadflow/OpenLoadFlowProviderTest.java
  src/test/java/com/powsybl/openloadflow/ac/NewtonKrylovTest.java
  src/test/java/com/powsybl/openloadflow/ac/solver/AcSolverFactoryTest.java
Labels: December 2024 release

#1136 Delete class MatrixUtil
  src/main/java/com/powsybl/openloadflow/network/LfAsymLineAdmittanceMatrix.java
  src/main/java/com/powsybl/openloadflow/util/MatrixUtil.java
Labels: December 2024 release

#1150 Bump powsybl-core to 6.6.0
  pom.xml
Labels: December 2024 release

#1157 Fix slack distribution outerloop incorrect stable status
  src/main/java/com/powsybl/openloadflow/network/util/ActivePowerDistribution.java
  src/test/java/com/powsybl/openloadflow/ac/DistributedSlackOnGenerationTest.java
  src/test/java/com/powsybl/openloadflow/network/DistributedSlackNetworkFactory.java
Labels: bug
