Repository powsybl/powsybl-open-loadflow, pull requests merged in 2024-07, with the labels that each got.

#1041 Fix limits handling in slack distribution on generators
  src/main/java/com/powsybl/openloadflow/ac/outerloop/DistributedSlackOuterLoop.java
  src/main/java/com/powsybl/openloadflow/network/BusDcState.java
  src/main/java/com/powsybl/openloadflow/network/LfAction.java
  src/main/java/com/powsybl/openloadflow/network/LfContingency.java
  src/main/java/com/powsybl/openloadflow/network/LfGenerator.java
  src/main/java/com/powsybl/openloadflow/network/NetworkState.java
  src/main/java/com/powsybl/openloadflow/network/impl/AbstractLfInjection.java
  src/main/java/com/powsybl/openloadflow/network/impl/LfVscConverterStationImpl.java
  src/main/java/com/powsybl/openloadflow/network/util/ActivePowerDistribution.java
  src/main/java/com/powsybl/openloadflow/network/util/GenerationActivePowerDistributionStep.java
  src/main/java/com/powsybl/openloadflow/network/util/LoadActivePowerDistributionStep.java
  src/main/java/com/powsybl/openloadflow/network/util/ParticipatingElement.java
  src/test/java/com/powsybl/openloadflow/ac/DistributedSlackOnGenerationTest.java
Labels: bug, PR: next-release, ready-for-review

#1043 Implement minTargetP and maxTargetP from ActivePowerControl extension
  src/main/java/com/powsybl/openloadflow/network/LargestGeneratorSlackBusSelector.java
  src/main/java/com/powsybl/openloadflow/network/LfAction.java
  src/main/java/com/powsybl/openloadflow/network/LfGenerator.java
  src/main/java/com/powsybl/openloadflow/network/LfNetwork.java
  src/main/java/com/powsybl/openloadflow/network/ReferenceBusGeneratorPrioritySelector.java
  src/main/java/com/powsybl/openloadflow/network/impl/AbstractLfBus.java
  src/main/java/com/powsybl/openloadflow/network/impl/AbstractLfGenerator.java
  src/main/java/com/powsybl/openloadflow/network/impl/LfBatteryImpl.java
  src/main/java/com/powsybl/openloadflow/network/impl/LfGeneratorImpl.java
  src/main/java/com/powsybl/openloadflow/network/util/GenerationActivePowerDistributionStep.java
  src/test/java/com/powsybl/openloadflow/ac/DistributedSlackOnGenerationTest.java
  src/test/resources/n.json
  src/test/resources/n2.json
Labels: PR: next-release

#1001 Refactor DC Sensitivity Analysis with Woodbury engine
  src/main/java/com/powsybl/openloadflow/dc/AbstractWoodburyEngineInputReader.java
  src/main/java/com/powsybl/openloadflow/dc/ComputedContingencyElement.java
  src/main/java/com/powsybl/openloadflow/dc/ConnectivityBreakAnalysis.java
  src/main/java/com/powsybl/openloadflow/dc/DcLoadFlowEngine.java
  src/main/java/com/powsybl/openloadflow/dc/WoodburyEngine.java
  src/main/java/com/powsybl/openloadflow/dc/WoodburyEngineInputReader.java
  src/main/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysis.java
  src/test/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysisTest.java
Labels: PR: next-release

#1058 Fix bus state for AC calculations
  src/main/java/com/powsybl/openloadflow/network/BusState.java
Labels: bug, PR: next-release

#1069 Security Analysis: Fix Generator initialTargetP in OperatorStrategies
  docs/index.md
  docs/loadflow/loadflow.md
  docs/loadflow/parameters.md
  docs/security/index.md
  docs/security/parameters.md
  docs/security/security.md
  docs/sensitivity/index.md
  docs/sensitivity/parameters.md
  docs/sensitivity/sensitivity.md
  src/main/java/com/powsybl/openloadflow/network/LfNetwork.java
  src/main/java/com/powsybl/openloadflow/network/NetworkState.java
  src/main/java/com/powsybl/openloadflow/sa/AbstractSecurityAnalysis.java
  src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisWithActionsTest.java
Labels: bug
