Repository powsybl/powsybl-open-loadflow, pull requests merged in 2025-03, with the labels that each got.

#1189 Balance type PROPORTIONAL_TO_REMAINING_MARGIN checks active mismatch sign for participation factors
  src/main/java/com/powsybl/openloadflow/network/util/ActivePowerDistribution.java
  src/main/java/com/powsybl/openloadflow/network/util/GenerationActivePowerDistributionStep.java
  src/main/java/com/powsybl/openloadflow/network/util/LoadActivePowerDistributionStep.java
  src/main/java/com/powsybl/openloadflow/sensi/AbstractSensitivityAnalysis.java
  src/test/java/com/powsybl/openloadflow/ac/DistributedSlackOnGenerationTest.java
Labels: Release 03/2025

#1187 Add decimal formatter to testing reports
  pom.xml
  src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowEurostagTutorialExample1Test.java
  src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowReportTest.java
  src/test/java/com/powsybl/openloadflow/dc/DcLoadFlowTest.java
  src/test/java/com/powsybl/openloadflow/util/LoadFlowAssert.java
  src/test/resources/areaInterchangeControlOuterLoop.txt
  src/test/resources/busAlreadyControlledWithDifferentTargetVReport.txt
  src/test/resources/controllerShuntAlreadyInVoltageControlReport.txt
  src/test/resources/detailedNrReportSecurityAnalysis.txt
  src/test/resources/esgTutoReport.txt
  src/test/resources/esgTutoReportDetailedNrReportLf.txt
  src/test/resources/esgTutoReportDetailedNrReportSensi.txt
  src/test/resources/generatorVoltageControlDiscarded.txt
  src/test/resources/generatorsConnectedToSameBusNotControllingSameBusReport.txt
  src/test/resources/multipleConnectedComponentsAcReport.txt
  src/test/resources/multipleConnectedComponentsDcReport.txt
  src/test/resources/notUniqueTargetVControllerBusReport.txt
  src/test/resources/saReport.txt
  src/test/resources/saReportOperatorStrategies.txt
  src/test/resources/saReportOperatorStrategyNoVoltageControl.txt
  src/test/resources/sharedGeneratorRemoteReactivePowerControlReport.txt
  src/test/resources/shuntVoltageControlDiscarded.txt
  src/test/resources/shuntVoltageControlOuterLoopReport.txt
  src/test/resources/transformerControlAlreadyExistsWithDifferentTargetVReport.txt
  src/test/resources/transformerReactivePowerControlOuterLoopReport.txt
  src/test/resources/transformerVoltageControlDiscarded.txt
Labels: ready-for-review, Release 03/2025, needs_core_rc

#1168 Fix SA reports in MT
  pom.xml
  src/main/java/com/powsybl/openloadflow/network/action/LfActionUtils.java
  src/main/java/com/powsybl/openloadflow/sa/AbstractSecurityAnalysis.java
  src/main/java/com/powsybl/openloadflow/sa/WoodburyDcSecurityAnalysis.java
  src/main/java/com/powsybl/openloadflow/util/Reports.java
  src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisTest.java
  src/test/resources/saMtReport.txt
Labels: bug, ready-for-review, needs_core_rc, Release 06/2025

#1182 Add PQ/PV switches to reports
  src/main/java/com/powsybl/openloadflow/ac/outerloop/ReactiveLimitsOuterLoop.java
  src/main/java/com/powsybl/openloadflow/util/Reports.java
  src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowTransformerReactivePowerControlTest.java
  src/test/java/com/powsybl/openloadflow/ac/GeneratorRemoteControlPQSwitchTest.java
  src/test/java/com/powsybl/openloadflow/ac/SecondaryVoltageControlTest.java
  src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisWithActionsTest.java
  src/test/java/com/powsybl/openloadflow/util/LoadFlowAssert.java
Labels: ready-for-review, Release 03/2025, needs_core_rc

#1208 fix pq switch report
  src/main/java/com/powsybl/openloadflow/ac/outerloop/ReactiveLimitsOuterLoop.java
  src/test/java/com/powsybl/openloadflow/ac/SwitchPqPvTest.java
Labels: bug, Release 03/2025

#1209 fix double slack distribution in SA DC
  src/main/java/com/powsybl/openloadflow/dc/DcLoadFlowEngine.java
  src/test/java/com/powsybl/openloadflow/sa/WoodburyDcSecurityAnalysisWithActionsTest.java
Labels: bug
