Repository powsybl/powsybl-open-loadflow, pull requests merged in 2025-02, with the labels that each got.

#1172 LfAction refactoring and area interchange target action support
  docs/security/inputs.md
  src/main/java/com/powsybl/openloadflow/NetworkCache.java
  src/main/java/com/powsybl/openloadflow/ac/outerloop/AutomationSystemOuterLoop.java
  src/main/java/com/powsybl/openloadflow/dc/fastdc/WoodburyEngine.java
  src/main/java/com/powsybl/openloadflow/network/LfAction.java
  src/main/java/com/powsybl/openloadflow/network/action/AbstractLfAction.java
  src/main/java/com/powsybl/openloadflow/network/action/AbstractLfBranchAction.java
  src/main/java/com/powsybl/openloadflow/network/action/AbstractLfTapChangerAction.java
  src/main/java/com/powsybl/openloadflow/network/action/LfAction.java
  src/main/java/com/powsybl/openloadflow/network/action/LfActionUtils.java
  src/main/java/com/powsybl/openloadflow/network/action/LfAreaInterchangeTargetAction.java
  src/main/java/com/powsybl/openloadflow/network/action/LfGeneratorAction.java
  src/main/java/com/powsybl/openloadflow/network/action/LfHvdcAction.java
  src/main/java/com/powsybl/openloadflow/network/action/LfLoadAction.java
  src/main/java/com/powsybl/openloadflow/network/action/LfPhaseTapChangerAction.java
  src/main/java/com/powsybl/openloadflow/network/action/LfRatioTapChangerAction.java
  src/main/java/com/powsybl/openloadflow/network/action/LfShuntCompensatorPositionAction.java
  src/main/java/com/powsybl/openloadflow/network/action/LfSwitchAction.java
  src/main/java/com/powsybl/openloadflow/network/action/LfTerminalsConnectionAction.java
  src/main/java/com/powsybl/openloadflow/sa/AbstractSecurityAnalysis.java
  src/main/java/com/powsybl/openloadflow/sa/WoodburyDcSecurityAnalysis.java
  src/test/java/com/powsybl/openloadflow/sa/LfActionTest.java
  src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisWithActionsTest.java
Labels: Release 03/2025

#1154 Add a parameter to force targetQ within reactive limits
  docs/loadflow/parameters.md
  src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java
  src/main/java/com/powsybl/openloadflow/network/LfNetworkParameters.java
  src/main/java/com/powsybl/openloadflow/network/impl/LfGeneratorImpl.java
  src/main/java/com/powsybl/openloadflow/sensi/AcSensitivityAnalysis.java
  src/test/java/com/powsybl/openloadflow/OpenLoadFlowParametersTest.java
  src/test/java/com/powsybl/openloadflow/OpenLoadFlowProviderTest.java
  src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowGeneratorTest.java
  src/test/resources/debug-parameters.json
Labels: ready-for-review, Release 03/2025

#1181 Support more voltage sensitivities cases
  docs/sensitivity/getting_started.md
  docs/sensitivity/index.md
  src/main/java/com/powsybl/openloadflow/sensi/AbstractSensitivityAnalysis.java
  src/test/java/com/powsybl/openloadflow/sensi/AbstractSensitivityAnalysisTest.java
  src/test/java/com/powsybl/openloadflow/sensi/AcSensiVoltageIeeeTest.java
Labels: Release 03/2025

#1173 Disable AC Emulation in Fast DC Security Analysis
  README.md
  docs/security/parameters.md
  src/main/java/com/powsybl/openloadflow/sa/WoodburyDcSecurityAnalysis.java
  src/main/java/com/powsybl/openloadflow/util/Reports.java
  src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisTest.java
Labels: ready-for-review

#1156 ContingencyLoadFlowParameters extension support in Security Analysis
  docs/security/parameters.md
  src/main/java/com/powsybl/openloadflow/LoadFlowParametersOverride.java
  src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java
  src/main/java/com/powsybl/openloadflow/lf/outerloop/config/AbstractAcOuterLoopConfig.java
  src/main/java/com/powsybl/openloadflow/lf/outerloop/config/AbstractDcOuterLoopConfig.java
  src/main/java/com/powsybl/openloadflow/lf/outerloop/config/DefaultAcOuterLoopConfig.java
  src/main/java/com/powsybl/openloadflow/lf/outerloop/config/DefaultDcOuterLoopConfig.java
  src/main/java/com/powsybl/openloadflow/lf/outerloop/config/ExplicitAcOuterLoopConfig.java
  src/main/java/com/powsybl/openloadflow/lf/outerloop/config/ExplicitDcOuterLoopConfig.java
  src/main/java/com/powsybl/openloadflow/lf/outerloop/config/OuterLoopConfig.java
  src/main/java/com/powsybl/openloadflow/network/action/LfAreaInterchangeTargetAction.java
  src/main/java/com/powsybl/openloadflow/sa/AbstractSecurityAnalysis.java
  src/main/java/com/powsybl/openloadflow/sa/AcSecurityAnalysis.java
  src/main/java/com/powsybl/openloadflow/sa/DcSecurityAnalysis.java
  src/main/java/com/powsybl/openloadflow/sa/WoodburyDcSecurityAnalysis.java
  src/main/java/com/powsybl/openloadflow/sa/extensions/ContingencyLoadFlowParameters.java
  src/main/java/com/powsybl/openloadflow/sa/extensions/ContingencyLoadFlowParametersJsonSerializer.java
  src/main/java/com/powsybl/openloadflow/sensi/AcSensitivityAnalysis.java
  src/test/java/com/powsybl/openloadflow/network/MultiAreaNetworkFactory.java
  src/test/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImplTest.java
  src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisTest.java
  src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisWithActionsTest.java
  src/test/java/com/powsybl/openloadflow/sa/extensions/OpenSecurityAnalysisExtensionsTest.java
  src/test/resources/contingencies.json
Labels: ready-for-review, Release 03/2025, Breaking Change

#1188 Move up unrealistic voltage check from NR to AC loadflow engine
  docs/loadflow/parameters.md
  src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java
  src/main/java/com/powsybl/openloadflow/ac/AcLoadFlowParameters.java
  src/main/java/com/powsybl/openloadflow/ac/AcloadFlowEngine.java
  src/main/java/com/powsybl/openloadflow/ac/solver/NewtonRaphson.java
  src/main/java/com/powsybl/openloadflow/ac/solver/NewtonRaphsonFactory.java
  src/main/java/com/powsybl/openloadflow/ac/solver/NewtonRaphsonParameters.java
  src/test/java/com/powsybl/openloadflow/OpenLoadFlowProviderTest.java
Labels: ready-for-review

#1179 Improve log and report when max outerloop iterations reached
  src/main/java/com/powsybl/openloadflow/ac/AcloadFlowEngine.java
  src/main/java/com/powsybl/openloadflow/dc/DcLoadFlowEngine.java
  src/main/java/com/powsybl/openloadflow/util/Reports.java
  src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowEurostagTutorialExample1Test.java
  src/test/java/com/powsybl/openloadflow/dc/DcLoadFlowTest.java
Labels: ready-for-review, Release 03/2025

#1190 Support ThreeWindingsTransformer in DC sensibility analysis
  docs/sensitivity/getting_started.md
  src/main/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysis.java
  src/test/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysisTest.java
Labels: ready-for-review, Release 03/2025

#1155 Security Analysis: custom redistribution of injections lost by the contingency
  docs/advanced_programming/contingency_active_power_loss.md
  docs/advanced_programming/external_ac_solver.md
  docs/advanced_programming/index.md
  docs/advanced_programming/lfnetwork_loader_postprocessor.md
  docs/advanced_programming/outerloop_configuration.md
  docs/index.md
  docs/security/parameters.md
  src/main/java/com/powsybl/openloadflow/sa/AbstractSecurityAnalysis.java
  src/main/java/com/powsybl/openloadflow/sa/ContingencyActivePowerLossDistribution.java
  src/main/java/com/powsybl/openloadflow/sa/DefaultContingencyActivePowerLossDistribution.java
  src/main/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisParameters.java
  src/main/java/com/powsybl/openloadflow/sa/WoodburyDcSecurityAnalysis.java
  src/main/java/com/powsybl/openloadflow/util/Reports.java
  src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisProviderTest.java
  src/test/resources/sa-params.json
  src/test/resources/saReport.txt
Labels: ready-for-review, Release 03/2025

#1185 Disable inconsistent generator voltage controls
  docs/loadflow/parameters.md
  src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java
  src/main/java/com/powsybl/openloadflow/network/LfNetworkParameters.java
  src/main/java/com/powsybl/openloadflow/network/impl/AbstractLfGenerator.java
  src/main/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImpl.java
  src/main/java/com/powsybl/openloadflow/network/impl/LfNetworkLoadingReport.java
  src/main/java/com/powsybl/openloadflow/sensi/AcSensitivityAnalysis.java
  src/main/java/com/powsybl/openloadflow/util/Reports.java
  src/test/java/com/powsybl/openloadflow/OpenLoadFlowParametersTest.java
  src/test/java/com/powsybl/openloadflow/OpenLoadFlowProviderTest.java
  src/test/java/com/powsybl/openloadflow/ac/GeneratorTargetVoltageInconsistencyTest.java
  src/test/resources/debug-parameters.json
  src/test/resources/generatorVoltageControlDiscarded.txt
Labels: ready-for-review, Release 03/2025

#1135 Reduce irrealistic voltage created by remote voltage control
  docs/loadflow/parameters.md
  src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java
  src/main/java/com/powsybl/openloadflow/ac/AcLoadFlowParameters.java
  src/main/java/com/powsybl/openloadflow/ac/AcloadFlowEngine.java
  src/main/java/com/powsybl/openloadflow/ac/outerloop/AcOuterLoop.java
  src/main/java/com/powsybl/openloadflow/ac/outerloop/ReactiveLimitsOuterLoop.java
  src/main/java/com/powsybl/openloadflow/ac/outerloop/TransformerVoltageControlOuterLoop.java
  src/main/java/com/powsybl/openloadflow/lf/outerloop/config/AbstractAcOuterLoopConfig.java
  src/main/java/com/powsybl/openloadflow/network/LfBus.java
  src/test/java/com/powsybl/openloadflow/OpenLoadFlowParametersTest.java
  src/test/java/com/powsybl/openloadflow/OpenLoadFlowProviderTest.java
  src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowReportTest.java
  src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowTransformerReactivePowerControlTest.java
  src/test/java/com/powsybl/openloadflow/ac/GeneratorRemoteControlPQSwitchTest.java
  src/test/resources/debug-parameters.json
Labels: ready-for-review, Release 03/2025

#1176 Adapt to change of LoadFlowProvider API + fix update to not write default values multiple times
  src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java
  src/main/java/com/powsybl/openloadflow/OpenLoadFlowProvider.java
  src/test/java/com/powsybl/openloadflow/OLFDefaultParametersLoaderMock.java
  src/test/java/com/powsybl/openloadflow/OpenLoadFlowParametersTest.java
  src/test/resources/OLFParametersUpdate.json
Labels: PR: next-release, Release 03/2025, needs_core_rc
