Repository powsybl/powsybl-open-loadflow, pull requests merged in 2025-06, with the labels that each got.

#1234 Fix slack distribution prop remaining margin up/down
  src/main/java/com/powsybl/openloadflow/network/util/ActivePowerDistribution.java
  src/main/java/com/powsybl/openloadflow/network/util/GenerationActivePowerDistributionStep.java
  src/main/java/com/powsybl/openloadflow/network/util/LoadActivePowerDistributionStep.java
  src/main/java/com/powsybl/openloadflow/sensi/AbstractSensitivityAnalysis.java
  src/test/java/com/powsybl/openloadflow/ac/DistributedSlackOnGenerationTest.java
Labels: bug

#1239 Adapt to the removal of PST FIXED_TAP regulation mode and the new PST…
  src/main/java/com/powsybl/openloadflow/network/impl/LfBranchImpl.java
  src/main/java/com/powsybl/openloadflow/network/impl/LfLegBranch.java
  src/main/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImpl.java
  src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowPhaseShifterTest.java
  src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowTransformerVoltageControlTest.java
  src/test/java/com/powsybl/openloadflow/network/NodeBreakerNetworkFactory.java
  src/test/java/com/powsybl/openloadflow/network/PhaseControlFactory.java
  src/test/java/com/powsybl/openloadflow/sa/WoodburyDcSecurityAnalysisWithActionsTest.java
  src/test/java/com/powsybl/openloadflow/sensi/AcSensitivityAnalysisTest.java
  src/test/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysisTest.java
Labels: Breaking Change, needs_core_rc, Release 06/2025

#1238 Adapt SVC with new regulating field replacing the old RegulationMode.OFF
  src/main/java/com/powsybl/openloadflow/network/impl/LfStaticVarCompensatorImpl.java
  src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowSvcTest.java
  src/test/java/com/powsybl/openloadflow/ac/SwitchPqPvTest.java
  src/test/java/com/powsybl/openloadflow/network/AbstractLoadFlowNetworkFactory.java
  src/test/java/com/powsybl/openloadflow/network/VoltageControlNetworkFactory.java
  src/test/java/com/powsybl/openloadflow/network/impl/LfBusImplTest.java
  src/test/java/com/powsybl/openloadflow/sensi/AcSensitivityAnalysisContingenciesTest.java
Labels: needs_core_rc, Release 06/2025

#1247 Rename test resources bundle
  src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowEurostagTutorialExample1Test.java
  src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowReportTest.java
  src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowShuntTest.java
  src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowTransformerReactivePowerControlTest.java
  src/test/java/com/powsybl/openloadflow/ac/GeneratorRemoteControlPQSwitchTest.java
  src/test/java/com/powsybl/openloadflow/ac/GeneratorRemoteControlTest.java
  src/test/java/com/powsybl/openloadflow/ac/GeneratorTargetVoltageInconsistencyTest.java
  src/test/java/com/powsybl/openloadflow/ac/SecondaryVoltageControlTest.java
  src/test/java/com/powsybl/openloadflow/ac/SwitchPqPvTest.java
  src/test/java/com/powsybl/openloadflow/dc/DcLoadFlowTest.java
  src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisTest.java
  src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisWithActionsTest.java
  src/test/java/com/powsybl/openloadflow/sensi/AcSensitivityAnalysisReportTest.java
  src/test/java/com/powsybl/openloadflow/util/ReportsTest.java
Labels: Release 06/2025

#1223 Fix slack mismatch remaining after AIC
  docs/loadflow/loadflow.md
  src/main/java/com/powsybl/openloadflow/lf/outerloop/AbstractAreaInterchangeControlOuterLoop.java
  src/test/java/com/powsybl/openloadflow/ac/AreaInterchangeControlTest.java
  src/test/java/com/powsybl/openloadflow/network/MultiAreaNetworkFactory.java
Labels: bug
