Repository powsybl/powsybl-open-loadflow, pull requests merged in 2025-01, with the labels that each got.

#1149 Enable download of documentation in pdf format
  docs/.readthedocs.yaml
Labels: Release 03/2025

#1160 Fix injections ignored on first slack bus when using multiple slacks
  src/main/java/com/powsybl/openloadflow/ac/AcTargetVector.java
  src/main/java/com/powsybl/openloadflow/ac/equations/AcEquationSystemCreator.java
  src/test/java/com/powsybl/openloadflow/ac/MultipleSlackBusesTest.java
Labels: ready-for-review, Release 03/2025

#1158 Refactor DC Outer Loops creation
  src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java
  src/main/java/com/powsybl/openloadflow/dc/DcAreaInterchangeControlControlOuterLoop.java
  src/main/java/com/powsybl/openloadflow/dc/DcAreaInterchangeControlOuterLoop.java
  src/main/java/com/powsybl/openloadflow/dc/DcLoadFlowEngine.java
  src/main/java/com/powsybl/openloadflow/dc/DcLoadFlowParameters.java
  src/main/java/com/powsybl/openloadflow/lf/outerloop/AbstractAreaInterchangeControlOuterLoop.java
  src/test/java/com/powsybl/openloadflow/OpenLoadFlowParametersTest.java
Labels: Release 03/2025

#1139 Contingency Load Flow parameters extension
  docs/security/parameters.md
  src/main/java/com/powsybl/openloadflow/sa/extensions/ContingencyLoadFlowParameters.java
  src/main/java/com/powsybl/openloadflow/sa/extensions/ContingencyLoadFlowParametersJsonSerializer.java
  src/test/java/com/powsybl/openloadflow/sa/extensions/OpenSecurityAnalysisExtensionsTest.java
  src/test/resources/contingencies.json
Labels: Release 03/2025

#1165 Fix secondary voltage control in case of generator remote voltage control
  docs/loadflow/parameters.md
  src/main/java/com/powsybl/openloadflow/ac/outerloop/SecondaryVoltageControlOuterLoop.java
  src/main/java/com/powsybl/openloadflow/network/GeneratorVoltageControl.java
  src/main/java/com/powsybl/openloadflow/network/LfSecondaryVoltageControl.java
  src/main/java/com/powsybl/openloadflow/network/impl/AbstractLfBus.java
  src/main/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImpl.java
  src/test/java/com/powsybl/openloadflow/ac/SecondaryVoltageControlTest.java
Labels: bug, Release 03/2025

#1142 Fix busbar section minimal tripping
  src/main/java/com/powsybl/openloadflow/network/impl/ContingencyTripping.java
  src/test/java/com/powsybl/openloadflow/util/sa/ContingencyTrippingTest.java
Labels: Release 03/2025

#1170 Modified exception message when initial LF fails in AC Sensi
  src/main/java/com/powsybl/openloadflow/sensi/AcSensitivityAnalysis.java
  src/test/java/com/powsybl/openloadflow/sensi/AcSensitivityAnalysisTest.java
Labels: ready-for-review, Release 03/2025

#1175 Fix doc for newtonRaphsonStoppingCriteriaType=UNIFORM_CRITERIA
  docs/loadflow/parameters.md
Labels: ready-for-review, Release 03/2025

#1159 Support outerLoopNames parameter in DC Load Flow
  docs/loadflow/parameters.md
  src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java
  src/main/java/com/powsybl/openloadflow/ac/outerloop/AcAreaInterchangeControlOuterLoop.java
  src/main/java/com/powsybl/openloadflow/ac/outerloop/AcIncrementalPhaseControlOuterLoop.java
  src/main/java/com/powsybl/openloadflow/dc/DcAreaInterchangeControlOuterLoop.java
  src/main/java/com/powsybl/openloadflow/dc/DcIncrementalPhaseControlOuterLoop.java
  src/main/java/com/powsybl/openloadflow/lf/outerloop/AbstractAreaInterchangeControlOuterLoop.java
  src/main/java/com/powsybl/openloadflow/lf/outerloop/AbstractIncrementalPhaseControlOuterLoop.java
  src/main/java/com/powsybl/openloadflow/lf/outerloop/config/AbstractAcOuterLoopConfig.java
  src/main/java/com/powsybl/openloadflow/lf/outerloop/config/AbstractDcOuterLoopConfig.java
  src/main/java/com/powsybl/openloadflow/lf/outerloop/config/AcOuterLoopConfig.java
  src/main/java/com/powsybl/openloadflow/lf/outerloop/config/DcOuterLoopConfig.java
  src/main/java/com/powsybl/openloadflow/lf/outerloop/config/DefaultAcOuterLoopConfig.java
  src/main/java/com/powsybl/openloadflow/lf/outerloop/config/DefaultDcOuterLoopConfig.java
  src/main/java/com/powsybl/openloadflow/lf/outerloop/config/ExplicitAcOuterLoopConfig.java
  src/main/java/com/powsybl/openloadflow/lf/outerloop/config/ExplicitDcOuterLoopConfig.java
  src/main/java/com/powsybl/openloadflow/lf/outerloop/config/OuterLoopConfig.java
  src/test/java/com/powsybl/openloadflow/OpenLoadFlowParametersTest.java
  src/test/java/com/powsybl/openloadflow/dc/DcLoadFlowTest.java
Labels: Release 03/2025, Breaking Change

#1177 Support operator strategies in MT
  src/main/java/com/powsybl/openloadflow/sa/AbstractSecurityAnalysis.java
  src/main/java/com/powsybl/openloadflow/sa/WoodburyDcSecurityAnalysis.java
  src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisTest.java
  src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisWithActionsTest.java
Labels: ready-for-review, Release 03/2025
