Repository powsybl/powsybl-open-loadflow, pull requests merged in 2025-04, with the labels that each got.

#1214 Fix parameters not read from platform config
  src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java
  src/test/java/com/powsybl/openloadflow/OpenLoadFlowParametersTest.java
Labels: bug

#1204 In Connectivity Report do not count twice lost loads and generators that are on a contingency bus
  src/main/java/com/powsybl/openloadflow/network/LfContingency.java
  src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisTest.java
Labels: bug

#1213 Remove network results and violation detection on disabled branches on one side in fast DC Security Analysis
  docs/security/parameters.md
  src/main/java/com/powsybl/openloadflow/dc/fastdc/ConnectivityBreakAnalysis.java
  src/main/java/com/powsybl/openloadflow/sa/AbstractNetworkResult.java
  src/main/java/com/powsybl/openloadflow/sa/LimitViolationManager.java
  src/main/java/com/powsybl/openloadflow/sa/PostContingencyNetworkResult.java
  src/main/java/com/powsybl/openloadflow/sa/PreContingencyNetworkResult.java
  src/main/java/com/powsybl/openloadflow/sa/WoodburyDcSecurityAnalysis.java
  src/test/java/com/powsybl/openloadflow/network/NodeBreakerNetworkFactory.java
  src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisTest.java
  src/test/java/com/powsybl/openloadflow/sa/WoodburyDcSecurityAnalysisWithActionsTest.java
Labels: bug

#1220 Filter disabled generators when computing bus Q limits
  src/main/java/com/powsybl/openloadflow/network/impl/AbstractLfBus.java
  src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisTest.java
Labels: bug

#1216 Reports i18n
  src/main/java/com/powsybl/openloadflow/ac/outerloop/ReactiveLimitsOuterLoop.java
  src/main/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImpl.java
  src/main/java/com/powsybl/openloadflow/sa/AbstractSecurityAnalysis.java
  src/main/java/com/powsybl/openloadflow/util/Reports.java
  src/main/java/com/powsybl/openloadflow/util/report/PowsyblOpenLoadFlowReportResourceBundle.java
  src/main/resources/com/powsybl/openloadflow/reports.properties
  src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowEurostagTutorialExample1Test.java
  src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowReportTest.java
  src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowShuntTest.java
  src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowTransformerReactivePowerControlTest.java
  src/test/java/com/powsybl/openloadflow/ac/DistributedSlackOnGenerationTest.java
  src/test/java/com/powsybl/openloadflow/ac/DistributedSlackOnLoadTest.java
  src/test/java/com/powsybl/openloadflow/ac/GeneratorRemoteControlPQSwitchTest.java
  src/test/java/com/powsybl/openloadflow/ac/GeneratorRemoteControlTest.java
  src/test/java/com/powsybl/openloadflow/ac/GeneratorTargetVoltageInconsistencyTest.java
  src/test/java/com/powsybl/openloadflow/ac/SecondaryVoltageControlTest.java
  src/test/java/com/powsybl/openloadflow/ac/SwitchPqPvTest.java
  src/test/java/com/powsybl/openloadflow/dc/DcLoadFlowTest.java
  src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisTest.java
  src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisWithActionsTest.java
  src/test/java/com/powsybl/openloadflow/sensi/AcSensitivityAnalysisReportTest.java
  src/test/java/com/powsybl/openloadflow/util/ReportsTest.java
  src/test/resources/i18n/reports.properties
  src/test/resources/i18n/reports_en.properties
  src/test/resources/i18n/reports_fr.properties
  src/test/resources/saMtReport.txt
Labels: Breaking Change, Release 06/2025

#1218 Force area boundary branches to min impedance
  docs/loadflow/loadflow.md
  src/main/java/com/powsybl/openloadflow/network/LfNetwork.java
  src/test/java/com/powsybl/openloadflow/ac/AreaInterchangeControlTest.java
Labels: bug

#1215 Active Power Distribution: better reports severities when residual mismatch remains
  src/main/java/com/powsybl/openloadflow/ac/outerloop/DistributedSlackOuterLoop.java
  src/main/java/com/powsybl/openloadflow/dc/DcLoadFlowEngine.java
  src/main/java/com/powsybl/openloadflow/util/Reports.java
  src/main/resources/com/powsybl/openloadflow/reports.properties
  src/test/java/com/powsybl/openloadflow/dc/DcLoadFlowTest.java
Labels: ready-for-review
